version: '3'
services:
  db:
    image: timescale/timescaledb
    container_name: dw-timescale-db
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: data-warehousing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
     - 5432:5432
