#CREATE DATABASE data-warehousing;

\c data-warehousing;

DROP TABLE IF EXISTS TWITTER CASCADE;

CREATE TABLE TWITTER(
   ID INT    NOT NULL,
   DATETIME     TIMESTAMP    NOT NULL,
   LANG           CHAR(5),
   USER_LOCATION  TEXT,
   TWEET     TEXT,
   TIDY_TWEET TEXT,
   POLARITY INT,
   SUBJECTIVITY INT
);



COPY TWITTER(ID,DATETIME,LANG,USER_LOCATION,TWEET,TIDY_TWEET,POLARITY,SUBJECTIVITY) FROM '/WarehousingtweetsCLEANED.csv' CSV;

SELECT COUNT(*) FROM TWITTER;

