CREATE DATABASE twitterdb;

\c twitterdb;

DROP TABLE IF EXISTS TWITTER CASCADE;

CREATE TABLE TWITTER(
   ID INT    NOT NULL,
   CREATED_AT     TIMESTAMP    NOT NULL,
   LANG           CHAR(5),
   USER_LOCATION  TEXT,
   TWEET     TEXT,
   TIDY_TWEET TEXT,
   SENTIMENT TEXT
);



COPY TWITTER(ID,CREATED_AT,LANG,USER_LOCATION,TWEET,TIDY_TWEET,SENTIMENT) FROM '/tweets.csv' CSV;

SELECT COUNT(*) FROM TWITTER;

